name: RF_distance
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - toyplot
  - toytree
  - biopython
  - ipykernel
  - jupyterlab
  - plotly
  - phyx
  - iqtree=2.3.6
